class AppConsts {
  static const String registerText = 'Register';
  static const String registerNowText = 'Register now';
  static const String loginText = 'Login';
  static const String notHaveAnAccountText = "Don't have an account?";
  static const String forgetPassText = 'Forgot your password?';
  static const String fullNameText = 'Full Name';
  static const String emailText = 'Email';
  static const String phoneNumberText = 'Phone';
  static const String cancel = 'Cancel';
  static const String passwordText = 'Password';
  static const String successMessage = 'User signed in successfully';
  static const String successMessageSignUp = 'User created successfully';
  static const String enterYourEmail = 'Please enter your email.';
  static const String enterYourFullName = 'Please enter your full name.';
  static const String enterYourPhoneNumber = 'Please enter your phone number.';
  static const String enterYourPassword = 'Please enter your password.';
  static const String rememberMeText = 'Remember me and keep me logged in';
  static const String policyMessage =
      'By creating an account, you agree to the terms and conditions.';
   static const String appName = 'UNKOWN';
  static const String skipButton = 'Skip';
  static const String notHaveAnAcountText = "don't have an acount?  ";
  static const String remebermeText = 'Remember me and keep me login';
  static const String toprecipes = 'Top Recipes';
  static const String seeall = 'See All';
  static String searchrecipes = 'Search Recipes';
  static String filter = "Filter";
  static String reset = "Reset";
  static String meal = "Meal";
  static String time = "Time";
  static String diffeculty = "Diffeculty";
  static String numofindredients = "Number Of Ingredients";
  static const String home = 'Home';
  static const String logout = 'Logout';
  static const String logoutMessage = 'Are you sure you want to logout?';
  static const String yes = 'Yes';
  static const String no = 'No';
  static const String logoutSuccess = 'Logout Success';
  static const String logoutFailed = 'Logout Failed';
  static const String profileHintText = 'Profile';
  static const String favorite = "Favorite";
  static const String userNameHintText = 'User Name';
  static const String emailHintText = 'Email';
  static const String phoneHintText = 'Phone';
  static const String passwordHintText = 'Enter New Password';
  static const String saveButton = 'Save';

}
